version: '3'

x-ruby-service: &ruby-service-base
  build:
    context: .
    dockerfile: ./Dockerfile
  depends_on:
    rabbitmq:
      condition: service_healthy
  networks:
    - microservices-network

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  operations-api:
    <<: *ruby-service-base
    container_name: operations-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
    command: ["ruby", "api/operations-api.rb", "-o", "0.0.0.0"]

  notifications-api:
    <<: *ruby-service-base
    container_name: notifications-api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app/api
    command: ["ruby", "api/notifications-api.rb", "-o", "0.0.0.0"]

  operations-consumer:
    <<: *ruby-service-base
    container_name: operations-consumer
    depends_on:
      notifications-api:
        condition: service_started
    volumes:
      - ./consumers:/app/consumers
      - ./data:/app/data
    command: ["ruby", "consumers/operations-consumer.rb"]

networks:
  microservices-network:
    driver: bridge